/**:
  ros__parameters:
    # --- General ITS Parameters ---
    sensor:
      id: "sensor_1"
      #id: "ft_sensor"

    fingertip:
      id: "link_3_0_tip"

      # Relative Tranformation from F/T Frame {S}, and Object Frame {B}
      displacement: # [mm]
        x: 8.0
        y: 0.0
        z: 0.0
      orientation: # [rad]
        roll: 0.0
        pitch: 1.5708
        yaw: 1.5708

      # fingertip Surface
      principalSemiAxis: # [mm]
        a: 15.0
        b: 24.5
        c: 15.0


    # --- Soft ITS & Solver Parameters ---
    soft_its:
      rate: 500.0
      wrench_msgs: true
      algorithm:
        verbose: false
        force_threshold: 0.5 # [N]
        method:
          name: "Closed-Form" # "Levenberg-Marquardt" | "Gauss-Newton" | "Closed-Form" | "Wrench-Method" | "Custom"

    # --- Visualization Parameters ---
    soft_viz:
      theme: "Dark" # "Dark" | "Light"

