# --- General ITS Parameters ---
sensor_1:
  sensor:
    id: "ft_sensor_1"

  fingertip:
    id: "myFinger_1"

    # Relative Tranformation from F/T Frame {S}, and Object Frame {B}
    displacement: # [m]
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: # [rad]
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

    # fingertip Surface
    principalSemiAxis: # [mm]
      a: 15.0
      b: 15.0
      c: 15.0

sensor_2:
  sensor:
    id: "ft_sensor_2"

  fingertip:
    id: "myFinger_2"

    # Relative Tranformation from F/T Frame {S}, and Object Frame {B}
    displacement: # [m]
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: # [rad]
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

    # fingertip Surface
    principalSemiAxis: # [mm]
      a: 15.0
      b: 15.0
      c: 15.0


# --- Soft ITS & Solver Parameters ---
soft_its:
  rate: 10.0
  wrench_msgs: true
  algorithm:
    verbose: true
    force_threshold: 0.5 # [N]
    method:
      name: "Closed-Form" # "Levenberg-Marquardt" | "Gauss-Newton" | "Closed-Form" | "Wrench-Method"
      params:
        count_max: 100 #100
        stop_threshold: 0.005
        epsilon: 1e-3 #0.01

# --- Visualization Parameters ---
soft_viz:
  theme: "Dark" # "Dark" | "Light"
